---
- name: Set installation facts
  ansible.builtin.include_tasks: vars.yml

- name: Manage PostgreSQL service
  ansible.builtin.service:
    name: "{{ _postgresql_service_name }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
  when: postgresql_package_state != 'absent'
